[package]
name = "maplewood"
version = "0.1.0"
authors = ["Kevin Hernandez-Rives <rurunosep@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.99.17"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["image", "ttf"]