[package]
authors = ["Kevin Hernandez-Rives <rurunosep@gmail.com>"]
edition = "2021"
name = "maplewood"
version = "0.1.0"

[dependencies]
array2d = "0.2.1"
derive-new = "0.5.9"
derive_more = "0.99.17"
indoc = "1.0.7"
rlua = "0.19.4"

[dependencies.sdl2]
default-features = false
features = ["image", "ttf"]
version = "0.35.2"
