[package]
authors = ["Kevin Hernandez-Rives <rurunosep@gmail.com>"]
edition = "2021"
name = "maplewood"
version = "0.1.0"

[dependencies]
array2d = "0.2.1"
derivative = "2.2.0"
derive-new = "0.5.9"
derive_more = "0.99.17"
indoc = "1.0.7"
itertools = "0.10.5"
rlua = "0.19.4"
sdl2 = {version = "0.35.2", features = ["image", "ttf", "mixer"]}

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features = ["winuser"]}
