[package]
authors = ["Kevin Hernandez-Rives <rurunosep@gmail.com>"]
edition = "2021"
name = "maplewood"
version = "0.2.1"

[dependencies]
anymap = "0.12.1"
colored = "2.1.0"
derivative = "2.2.0"
derive_more = "0.99.17"
euclid = "0.22.9"
itertools = "0.11.0"
log = {version = "0.4.22", features = ["std", "kv"]}
rlua = "0.19.4"
sdl2 = {version = "0.35.2", features = ["image", "ttf", "mixer"]}
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
slotmap = "1.0.6"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features = ["winuser"]}
