unstable_features = true
use_small_heuristics = "Max"
max_width = 90
use_field_init_shorthand = true
where_single_line = true
brace_style = "PreferSameLine"
wrap_comments = true
normalize_comments = true
format_strings = true